mkdir _Game
touch _Game/.gitkeep
mkdir _Game/Animation
touch _Game/Animation/.gitkeep
mkdir _Game/Art
touch _Game/Art/.gitkeep
mkdir _Game/Art/Materials
touch _Game/Art/Materials/.gitkeep
mkdir _Game/Art/Models
touch _Game/Art/Models/.gitkeep
mkdir _Game/Art/Sprites
touch _Game/Art/Sprites/.gitkeep
mkdir _Game/Audio
touch _Game/Audio/.gitkeep
mkdir _Game/Audio/Music
touch _Game/Audio/Music/.gitkeep
mkdir _Game/Audio/Sounds
touch _Game/Audio/Sounds/.gitkeep
mkdir _Game/Editor
touch _Game/Editor/.gitkeep
mkdir _Game/Fonts
touch _Game/Fonts/.gitkeep
mkdir _Game/Prefabs
touch _Game/Prefabs/.gitkeep
mkdir _Game/Scenes
touch _Game/Scenes/.gitkeep
mkdir _Game/Scenes/TestScenes
touch _Game/Scenes/TestScenes/.gitkeep
mkdir _Game/Scripts
touch _Game/Scripts/.gitkeep
mkdir _Game/Scripts/Game
touch _Game/Scripts/Game/.gitkeep
mkdir _Game/Scripts/Managers
touch _Game/Scripts/Managers/.gitkeep
mkdir _Game/Scripts/UI
touch _Game/Scripts/UI/.gitkeep
mkdir _Game/Scripts/Utilities
touch _Game/Scripts/Utilities/.gitkeep
mkdir _Game/Settings
touch _Game/Settings/.gitkeep